name: Generate snake animation

on:
  # Run automatically every 24 hours
  schedule:
    - cron: "0 */24 * * *"
  
  # Allow manual run
  workflow_dispatch:
  
  # Run on every push to the main branch
  push:
    branches:
      - main

jobs:
  generate:
    permissions: 
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5
    
    steps:
      # Generate a snake game from a GitHub user's contributions graph, outputting an SVG animation
      - name: Generate GitHub contribution grid snake
        uses: BiaAlverne/snk/svg-only@v0
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?hide_stack=true&snake_size=5&color_snake=red&speed=auto
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&hide_stack=true&snake_size=5&color_snake=red&speed=auto
          
      # Push the content of build_dir to a branch
      # The content will be available at https://raw.githubusercontent.com/<github_user>/<repository>/<target_branch>/<file>, or as a GitHub page
      - name: Push GitHub contribution grid snake SVG to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
